/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moneybank;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.proteanit.sql.DbUtils;
import java.awt.image.BufferedImage;
import java.text.MessageFormat;
import javax.swing.JTable;

/**
 *
 * @author tyagi
 */
public class CustomerMain extends javax.swing.JFrame {

    static String Username;
    int positionX = 0, positionY = 0;
    byte[ ] image = null;
    int cBal, nBal, tBal, MinB;
    String username= null,email = null,district = null,pincode = null, acctype = null , pwd = null, balance = null, accNo = null,lname = null,fname = null,phone = null, address = null, country = null;
    String state = null, minb = "0", toAcc = null, toAccBal = null, gender = null;
    String timeStamp = new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss").format(new java.util.Date());
    private BufferedImage image1;
    public CustomerMain(String Username) {
        this.Username = Username;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titlebar = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        ProfileNav = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        CheckBalNav = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        DepositeMonNav = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        WithdrawMonNav = new javax.swing.JPanel();
        ind_5 = new javax.swing.JPanel();
        TransferMonNav = new javax.swing.JPanel();
        ind_6 = new javax.swing.JPanel();
        SettingNav = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CMainToggel = new javax.swing.JTabbedPane();
        ProfileP = new javax.swing.JTabbedPane();
        Profile = new javax.swing.JPanel();
        ProfilePic = new javax.swing.JLabel();
        PUsername = new javax.swing.JLabel();
        PAccountNo = new javax.swing.JLabel();
        PName = new javax.swing.JLabel();
        PEmail = new javax.swing.JLabel();
        PPhone = new javax.swing.JLabel();
        PState = new javax.swing.JLabel();
        PAddress = new javax.swing.JTextArea();
        PCountry = new javax.swing.JLabel();
        PAccType = new javax.swing.JLabel();
        PGetStatementB = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        CheckBalP = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        CheckBalL = new javax.swing.JLabel();
        CheckBalB = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        DepositeP = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        DCurrentBalL = new javax.swing.JLabel();
        DAmountF = new javax.swing.JTextField();
        DepositB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        WithdrawP = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        WCurrentBalL = new javax.swing.JLabel();
        WAmountF = new javax.swing.JTextField();
        WithdrawB = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TransferP = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        TCurrentBalL = new javax.swing.JLabel();
        ToAccountF = new javax.swing.JTextField();
        TAmountF = new javax.swing.JTextField();
        TransferB = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        SettingP = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        SNameL = new javax.swing.JLabel();
        SEmailL = new javax.swing.JLabel();
        SPhoneL = new javax.swing.JLabel();
        SAddressF = new javax.swing.JTextArea();
        SOldPasswordF = new javax.swing.JPasswordField();
        SPasswordF = new javax.swing.JPasswordField();
        SCnfPasswordF = new javax.swing.JPasswordField();
        SUpdateB = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        StatementP = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StatementT = new javax.swing.JTable();
        SAccountNo = new javax.swing.JLabel();
        SDownloadB = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        Titlebar.setBackground(new java.awt.Color(23, 35, 51));
        Titlebar.setLayout(null);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneybank/images/delete_32px.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        Titlebar.add(Exit);
        Exit.setBounds(1570, 0, 41, 40);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneybank/images/newlogout.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        Titlebar.add(logout);
        logout.setBounds(1530, 0, 40, 40);

        Title.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(188, 167, 251));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Online Banking MoneyApp");
        Titlebar.add(Title);
        Title.setBounds(0, 0, 1570, 40);

        jPanel1.add(Titlebar);
        Titlebar.setBounds(0, 0, 1610, 40);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        ind_1.setBackground(new java.awt.Color(188, 167, 251));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel3.add(ind_1);
        ind_1.setBounds(0, 225, 10, 80);

        ProfileNav.setBackground(new java.awt.Color(163, 186, 255));
        ProfileNav.setOpaque(false);
        ProfileNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProfileNavMousePressed(evt);
            }
        });
        ProfileNav.setLayout(null);
        jPanel3.add(ProfileNav);
        ProfileNav.setBounds(10, 225, 300, 80);

        ind_2.setBackground(new java.awt.Color(5, 27, 70));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel3.add(ind_2);
        ind_2.setBounds(0, 305, 10, 80);

        CheckBalNav.setBackground(new java.awt.Color(163, 186, 255));
        CheckBalNav.setOpaque(false);
        CheckBalNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CheckBalNavMousePressed(evt);
            }
        });
        CheckBalNav.setLayout(null);
        jPanel3.add(CheckBalNav);
        CheckBalNav.setBounds(10, 305, 300, 80);

        ind_3.setBackground(new java.awt.Color(5, 27, 70));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        jPanel3.add(ind_3);
        ind_3.setBounds(0, 385, 10, 75);

        DepositeMonNav.setBackground(new java.awt.Color(163, 186, 255));
        DepositeMonNav.setOpaque(false);
        DepositeMonNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DepositeMonNavMousePressed(evt);
            }
        });
        DepositeMonNav.setLayout(null);
        jPanel3.add(DepositeMonNav);
        DepositeMonNav.setBounds(10, 385, 300, 75);

        ind_4.setBackground(new java.awt.Color(5, 27, 70));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        jPanel3.add(ind_4);
        ind_4.setBounds(0, 460, 10, 75);

        WithdrawMonNav.setBackground(new java.awt.Color(163, 186, 255));
        WithdrawMonNav.setOpaque(false);
        WithdrawMonNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                WithdrawMonNavMousePressed(evt);
            }
        });
        WithdrawMonNav.setLayout(null);
        jPanel3.add(WithdrawMonNav);
        WithdrawMonNav.setBounds(10, 460, 300, 75);

        ind_5.setBackground(new java.awt.Color(5, 27, 70));

        javax.swing.GroupLayout ind_5Layout = new javax.swing.GroupLayout(ind_5);
        ind_5.setLayout(ind_5Layout);
        ind_5Layout.setHorizontalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ind_5Layout.setVerticalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        jPanel3.add(ind_5);
        ind_5.setBounds(0, 535, 10, 75);

        TransferMonNav.setBackground(new java.awt.Color(163, 186, 255));
        TransferMonNav.setOpaque(false);
        TransferMonNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TransferMonNavMousePressed(evt);
            }
        });
        TransferMonNav.setLayout(null);
        jPanel3.add(TransferMonNav);
        TransferMonNav.setBounds(10, 535, 300, 75);

        ind_6.setBackground(new java.awt.Color(5, 27, 70));

        javax.swing.GroupLayout ind_6Layout = new javax.swing.GroupLayout(ind_6);
        ind_6.setLayout(ind_6Layout);
        ind_6Layout.setHorizontalGroup(
            ind_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ind_6Layout.setVerticalGroup(
            ind_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        jPanel3.add(ind_6);
        ind_6.setBounds(0, 610, 10, 75);

        SettingNav.setBackground(new java.awt.Color(163, 186, 255));
        SettingNav.setOpaque(false);
        SettingNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SettingNavMousePressed(evt);
            }
        });
        SettingNav.setLayout(null);
        jPanel3.add(SettingNav);
        SettingNav.setBounds(10, 610, 300, 75);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneybank/images/NAV4.png"))); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 310, 770);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 40, 310, 780);

        ProfileP.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ProfilePComponentShown(evt);
            }
        });

        Profile.setBackground(new java.awt.Color(90, 102, 123));

        ProfilePic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfilePic.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        PUsername.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        PUsername.setForeground(new java.awt.Color(255, 102, 102));
        PUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        PAccountNo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        PAccountNo.setForeground(new java.awt.Color(255, 255, 255));
        PAccountNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        PName.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        PName.setForeground(new java.awt.Color(255, 255, 255));
        PName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        PEmail.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        PEmail.setForeground(new java.awt.Color(255, 255, 255));
        PEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        PPhone.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        PPhone.setForeground(new java.awt.Color(255, 255, 255));
        PPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        PState.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        PState.setForeground(new java.awt.Color(255, 255, 255));
        PState.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        PAddress.setEditable(false);
        PAddress.setBackground(new java.awt.Color(90, 102, 123));
        PAddress.setColumns(20);
        PAddress.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        PAddress.setForeground(new java.awt.Color(255, 255, 255));
        PAddress.setLineWrap(true);
        PAddress.setRows(5);
        PAddress.setWrapStyleWord(true);
        PAddress.setFocusable(false);
        PAddress.setOpaque(false);
        PAddress.setRequestFocusEnabled(false);
        PAddress.setVerifyInputWhenFocusTarget(false);

        PCountry.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        PCountry.setForeground(new java.awt.Color(255, 255, 255));
        PCountry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        PAccType.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        PAccType.setForeground(new java.awt.Color(255, 255, 255));
        PAccType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        PGetStatementB.setBorder(null);
        PGetStatementB.setBorderPainted(false);
        PGetStatementB.setContentAreaFilled(false);
        PGetStatementB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PGetStatementBMouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneybank/images/profile.png"))); // NOI18N

        javax.swing.GroupLayout ProfileLayout = new javax.swing.GroupLayout(Profile);
        Profile.setLayout(ProfileLayout);
        ProfileLayout.setHorizontalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGap(510, 510, 510)
                        .addComponent(PUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(PAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(PState, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(PCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGap(550, 550, 550)
                        .addComponent(PGetStatementB, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(PEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGap(900, 900, 900)
                        .addComponent(PAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGap(900, 900, 900)
                        .addComponent(PName, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(PAccType, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGap(900, 900, 900)
                        .addComponent(PPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGap(556, 556, 556)
                        .addComponent(ProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProfileLayout.setVerticalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(PUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(PAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(PState, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(PCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(PGetStatementB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(PEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(ProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addComponent(PAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(PName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGap(632, 632, 632)
                .addComponent(PAccType, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(PPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel8)
        );

        ProfileP.addTab("tab1", Profile);

        CMainToggel.addTab("", ProfileP);

        jPanel4.setLayout(null);

        CheckBalL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CheckBalL.setForeground(new java.awt.Color(255, 153, 153));
        CheckBalL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(CheckBalL);
        CheckBalL.setBounds(80, 350, 340, 50);

        CheckBalB.setContentAreaFilled(false);
        CheckBalB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBalBActionPerformed(evt);
            }
        });
        jPanel4.add(CheckBalB);
        CheckBalB.setBounds(80, 440, 340, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneybank/images/check baalnceP.png"))); // NOI18N
        jPanel4.add(jLabel4);
        jLabel4.setBounds(0, 0, 1300, 780);

        CheckBalP.addTab("tab1", jPanel4);

        CMainToggel.addTab("", CheckBalP);

        DepositeP.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                DepositePComponentShown(evt);
            }
        });

        jPanel2.setLayout(null);

        DCurrentBalL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DCurrentBalL.setForeground(new java.awt.Color(255, 153, 153));
        DCurrentBalL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(DCurrentBalL);
        DCurrentBalL.setBounds(70, 330, 350, 40);

        DAmountF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DAmountF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DAmountF.setBorder(null);
        DAmountF.setOpaque(false);
        jPanel2.add(DAmountF);
        DAmountF.setBounds(60, 420, 360, 50);

        DepositB.setContentAreaFilled(false);
        DepositB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositBActionPerformed(evt);
            }
        });
        jPanel2.add(DepositB);
        DepositB.setBounds(60, 490, 350, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneybank/images/Deposit Money1.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 1300, 780);

        DepositeP.addTab("tab1", jPanel2);

        CMainToggel.addTab("", DepositeP);

        WithdrawP.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                WithdrawPComponentShown(evt);
            }
        });

        jPanel5.setLayout(null);

        WCurrentBalL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        WCurrentBalL.setForeground(new java.awt.Color(255, 153, 153));
        WCurrentBalL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(WCurrentBalL);
        WCurrentBalL.setBounds(70, 330, 350, 40);

        WAmountF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        WAmountF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        WAmountF.setBorder(null);
        WAmountF.setOpaque(false);
        jPanel5.add(WAmountF);
        WAmountF.setBounds(60, 420, 360, 50);

        WithdrawB.setContentAreaFilled(false);
        WithdrawB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawBActionPerformed(evt);
            }
        });
        jPanel5.add(WithdrawB);
        WithdrawB.setBounds(60, 490, 350, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneybank/images/Withdraw Moneyt.png"))); // NOI18N
        jPanel5.add(jLabel5);
        jLabel5.setBounds(0, 0, 1300, 780);

        WithdrawP.addTab("tab1", jPanel5);

        CMainToggel.addTab("", WithdrawP);

        TransferP.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                TransferPComponentShown(evt);
            }
        });

        jPanel6.setLayout(null);

        TCurrentBalL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TCurrentBalL.setForeground(new java.awt.Color(255, 153, 153));
        TCurrentBalL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(TCurrentBalL);
        TCurrentBalL.setBounds(70, 240, 350, 40);

        ToAccountF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ToAccountF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ToAccountF.setBorder(null);
        ToAccountF.setOpaque(false);
        jPanel6.add(ToAccountF);
        ToAccountF.setBounds(60, 330, 360, 50);

        TAmountF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TAmountF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TAmountF.setBorder(null);
        TAmountF.setOpaque(false);
        jPanel6.add(TAmountF);
        TAmountF.setBounds(60, 420, 360, 50);

        TransferB.setContentAreaFilled(false);
        TransferB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferBActionPerformed(evt);
            }
        });
        jPanel6.add(TransferB);
        TransferB.setBounds(60, 490, 350, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneybank/images/Transfer Money2.png"))); // NOI18N
        jPanel6.add(jLabel6);
        jLabel6.setBounds(0, 0, 1300, 780);

        TransferP.addTab("tab1", jPanel6);

        CMainToggel.addTab("", TransferP);

        SettingP.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                SettingPComponentShown(evt);
            }
        });

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SNameL.setBackground(new java.awt.Color(116, 125, 142));
        SNameL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SNameL.setForeground(new java.awt.Color(255, 255, 255));
        SNameL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel7.add(SNameL, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 490, 30));

        SEmailL.setBackground(new java.awt.Color(116, 125, 142));
        SEmailL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SEmailL.setForeground(new java.awt.Color(255, 255, 255));
        SEmailL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel7.add(SEmailL, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 480, 40));

        SPhoneL.setBackground(new java.awt.Color(116, 125, 142));
        SPhoneL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SPhoneL.setForeground(new java.awt.Color(255, 255, 255));
        SPhoneL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel7.add(SPhoneL, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 490, 40));

        SAddressF.setBackground(new java.awt.Color(116, 125, 142));
        SAddressF.setColumns(20);
        SAddressF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SAddressF.setForeground(new java.awt.Color(255, 255, 255));
        SAddressF.setLineWrap(true);
        SAddressF.setRows(5);
        SAddressF.setWrapStyleWord(true);
        SAddressF.setOpaque(false);
        jPanel7.add(SAddressF, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 300, 480, 170));

        SOldPasswordF.setBackground(new java.awt.Color(116, 125, 142));
        SOldPasswordF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SOldPasswordF.setForeground(new java.awt.Color(255, 255, 255));
        SOldPasswordF.setBorder(null);
        SOldPasswordF.setOpaque(false);
        jPanel7.add(SOldPasswordF, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 490, 30));

        SPasswordF.setBackground(new java.awt.Color(116, 125, 142));
        SPasswordF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SPasswordF.setForeground(new java.awt.Color(255, 255, 255));
        SPasswordF.setBorder(null);
        SPasswordF.setOpaque(false);
        jPanel7.add(SPasswordF, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 570, 480, 40));

        SCnfPasswordF.setBackground(new java.awt.Color(116, 125, 142));
        SCnfPasswordF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SCnfPasswordF.setForeground(new java.awt.Color(255, 255, 255));
        SCnfPasswordF.setBorder(null);
        SCnfPasswordF.setOpaque(false);
        jPanel7.add(SCnfPasswordF, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 640, 480, 40));

        SUpdateB.setContentAreaFilled(false);
        SUpdateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUpdateBActionPerformed(evt);
            }
        });
        jPanel7.add(SUpdateB, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 700, 190, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneybank/images/Updatedata.png"))); // NOI18N
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        SettingP.addTab("tab1", jPanel7);

        CMainToggel.addTab("", SettingP);

        StatementP.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                StatementPComponentShown(evt);
            }
        });

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setOpaque(false);

        StatementT.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        StatementT.setOpaque(false);
        StatementT.setRowHeight(40);
        StatementT.setRowSelectionAllowed(false);
        StatementT.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(StatementT);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 1170, 450));

        SAccountNo.setBackground(new java.awt.Color(255, 255, 255));
        SAccountNo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SAccountNo.setForeground(new java.awt.Color(255, 153, 153));
        SAccountNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel8.add(SAccountNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 260, 50));

        SDownloadB.setContentAreaFilled(false);
        SDownloadB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SDownloadBActionPerformed(evt);
            }
        });
        jPanel8.add(SDownloadB, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 690, 250, 50));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneybank/images/statement.png"))); // NOI18N
        jLabel9.setText("jdjhjhdcbn");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        StatementP.addTab("tab1", jPanel8);

        CMainToggel.addTab("", StatementP);

        jPanel1.add(CMainToggel);
        CMainToggel.setBounds(310, -20, 1300, 830);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1611, 812));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_ExitMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Home1 hm = new Home1();
        hm.setVisible(true);
        setVisible(false);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void ProfileNavMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileNavMousePressed
        setColor(ind_1);
        resetColor(new JPanel[]{ind_2,ind_3,ind_4,ind_5,ind_6}, new JPanel[]{CheckBalNav,DepositeMonNav,WithdrawMonNav,TransferMonNav,SettingNav,SettingNav});
        CMainToggel.setSelectedIndex(0);
    }//GEN-LAST:event_ProfileNavMousePressed

    private void CheckBalNavMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckBalNavMousePressed
        setColor(ind_2);
        resetColor(new JPanel[]{ind_1,ind_3,ind_4,ind_5,ind_6}, new JPanel[]{ProfileNav,DepositeMonNav,WithdrawMonNav,TransferMonNav,SettingNav,SettingNav});
        CMainToggel.setSelectedIndex(1);
    }//GEN-LAST:event_CheckBalNavMousePressed

    private void DepositeMonNavMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepositeMonNavMousePressed
        setColor(ind_3);
        resetColor(new JPanel[]{ind_2,ind_1,ind_4,ind_5,ind_6}, new JPanel[]{CheckBalNav,ProfileNav,WithdrawMonNav,TransferMonNav,SettingNav,SettingNav});
        CMainToggel.setSelectedIndex(2);
    }//GEN-LAST:event_DepositeMonNavMousePressed

    private void WithdrawMonNavMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WithdrawMonNavMousePressed
        setColor(ind_4);
        resetColor(new JPanel[]{ind_3,ind_2,ind_1,ind_5,ind_6}, new JPanel[]{DepositeMonNav,CheckBalNav,ProfileNav,TransferMonNav,SettingNav,SettingNav});
        CMainToggel.setSelectedIndex(3);
    }//GEN-LAST:event_WithdrawMonNavMousePressed

    private void TransferMonNavMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransferMonNavMousePressed
        setColor(ind_5);
        resetColor(new JPanel[]{ind_4,ind_3,ind_2,ind_1,ind_6}, new JPanel[]{WithdrawMonNav,DepositeMonNav,CheckBalNav,ProfileNav,SettingNav,SettingNav});
        CMainToggel.setSelectedIndex(4);
    }//GEN-LAST:event_TransferMonNavMousePressed

    private void SettingNavMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingNavMousePressed
        setColor(ind_6);
        resetColor(new JPanel[]{ind_5,ind_4,ind_3,ind_2,ind_1}, new JPanel[]{TransferMonNav,WithdrawMonNav,DepositeMonNav,CheckBalNav,ProfileNav,SettingNav});
        CMainToggel.setSelectedIndex(5);
    }//GEN-LAST:event_SettingNavMousePressed

    private void PGetStatementBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PGetStatementBMouseClicked
        CMainToggel.setSelectedIndex(6);
    }//GEN-LAST:event_PGetStatementBMouseClicked

    private void CheckBalBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBalBActionPerformed
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpd", "root", "Tyagi67@#");
            PreparedStatement ps = con.prepareStatement("select * from customerlogin where Username ='"+Username+"'");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                balance = rs.getString("Balance");
            }
            
            String string = "\u20B9";
            byte[] utf8 = string.getBytes("UTF-8");
            string = new String(utf8, "UTF-8");
            CheckBalL.setText(string + " " + balance);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
            
        }
    }//GEN-LAST:event_CheckBalBActionPerformed

    private void DepositBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositBActionPerformed
        
        try{
             Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpd", "root", "Tyagi67@#");
            PreparedStatement ps1 = con.prepareStatement("update customerlogin set Balance =? where AccountNumber=?");
             PreparedStatement ps = con.prepareStatement("select * from customerlogin where Username ='"+Username+"'");
             PreparedStatement ps2 = con.prepareStatement("insert into transactions(AccountNumber,Date, Credit, ClearBalance) values(?,?,?,?)");
             ResultSet rs = ps.executeQuery();
            while(rs.next()){
                balance = rs.getString("Balance");
                accNo = rs.getString("AccountNumber");
            }
            
            cBal = Integer.parseInt(balance);
            nBal = Integer.parseInt(DAmountF.getText());
            
            if(nBal <= MinB)
                {
                    JOptionPane.showMessageDialog(rootPane,"Deposit bellow Amount zero is not allowed!. " + nBal);
                }
            else
            {
                 tBal = cBal + nBal;
        
                ps1.setString(1, String.valueOf(tBal));
                ps1.setString(2, accNo);
                ps2.setString(1, accNo);
                ps2.setString(2, timeStamp);
                ps2.setString(3, String.valueOf(nBal));
                ps2.setString(4, String.valueOf(tBal));

                int i = ps1.executeUpdate();
                int j = ps2.executeUpdate();
                if(i == 1 && j==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"You have sussesfully Deposit Rs. " + nBal);
                    CustomerMain cm = new CustomerMain(Username);
                    cm.setVisible(true);
                    setVisible(false);
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane,"Some Error Occured, try again! ");
                    DCurrentBalL.setText("");
                    DAmountF.setText("");
                }
                }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_DepositBActionPerformed

    private void WithdrawBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawBActionPerformed
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpd", "root", "Tyagi67@#");
            PreparedStatement ps = con.prepareStatement("select * from customerlogin where Username ='"+Username+"'");
            PreparedStatement ps1 = con.prepareStatement("update customerlogin set Balance =? where AccountNumber=?");
            PreparedStatement ps2 = con.prepareStatement("insert into transactions(AccountNumber,Date, Debit, ClearBalance) values(?,?,?,?)");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                balance = rs.getString("Balance");
                accNo = rs.getString("AccountNumber");
            }
                cBal = Integer.parseInt(balance);
                nBal = Integer.parseInt(WAmountF.getText());
                if(nBal > cBal)
                {
                    JOptionPane.showMessageDialog(rootPane,"Do Not Have Sufficient Money!. " + cBal);
                }
                else
                {
                tBal = cBal - nBal;
        
                ps1.setString(1, String.valueOf(tBal));
                ps1.setString(2, accNo);
                ps2.setString(1, accNo);
                ps2.setString(2, timeStamp);
                ps2.setString(3, String.valueOf(nBal));
                ps2.setString(4, String.valueOf(tBal));

                int i = ps1.executeUpdate();
                int j = ps2.executeUpdate();
                if(i == 1 && j == 1)
                {
                    JOptionPane.showMessageDialog(rootPane,"You have sussesfully Withdraw Rs. " + nBal);
                    CustomerMain cm = new CustomerMain(Username);
                    cm.setVisible(true);
                    setVisible(false);
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane,"Some Error Occured, try again! ");
                    WAmountF.setText("");
                }
                }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_WithdrawBActionPerformed

    
    void retrieveBal()
        {
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpd", "root", "Tyagi67@#");
                PreparedStatement ps = con.prepareStatement("select * from customerlogin where AccountNumber='"+toAcc+"'");
                
                ResultSet rs = ps.executeQuery();
                while(rs.next())
                {
                    toAccBal = rs.getString("Balance");
                }

            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
        }
    
    
    
    private void TransferBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferBActionPerformed
        int cBal = Integer.parseInt(balance);
        int amt = Integer.parseInt(TAmountF.getText());
        toAcc = ToAccountF.getText();
        retrieveBal();
        int toAccBal2 = Integer.parseInt(toAccBal);
        int totalNewBal = amt + toAccBal2;
        int i, j =0;
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpd", "root", "Tyagi67@#");
            PreparedStatement ps = con.prepareStatement("update customerlogin set Balance=? where AccountNumber=?");
            PreparedStatement ps1 = con.prepareStatement("insert into transactions(AccountNumber, Date, Credit, ClearBalance) values(?,?,?,?)");
            
            if(amt <= cBal)
            {
            ps.setString(1, String.valueOf(totalNewBal));
            ps.setString(2, toAcc);
            ps1.setString(1, toAcc);
            ps1.setString(2, timeStamp);
            ps1.setString(3, String.valueOf(amt));
            ps1.setString(4, String.valueOf(totalNewBal));
            
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Do not have Sufficient Balance!, Try again!");
            }
            i = ps.executeUpdate();
            j = ps1.executeUpdate();
            if (i == 1 && j == 1) {
                JOptionPane.showMessageDialog(rootPane, "You have succesfully Transferred Rs."+amt+ " to "+toAcc);
                CustomerMain cm = new CustomerMain(Username);
                cm.setVisible(true);
                setVisible(false);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Some error occured, try again!");
                
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
        
         int myBal = Integer.parseInt(balance);
        myBal = myBal - amt;

        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpd", "root", "Tyagi67@#");
            PreparedStatement ps = con.prepareStatement("update customerlogin set Balance=? where AccountNumber=?");
            PreparedStatement ps1 = con.prepareStatement("insert into transactions(AccountNumber,Date, Debit, ClearBalance) values(?,?,?,?)");
            ps.setString(1, String.valueOf(myBal));
            ps.setString(2, accNo);
            ps1.setString(1, accNo);
            ps1.setString(2, timeStamp);
            ps1.setString(3, String.valueOf(amt));
            ps1.setString(4, String.valueOf(myBal));
            i = ps.executeUpdate();
            j = ps1.executeUpdate();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_TransferBActionPerformed

    private void SUpdateBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUpdateBActionPerformed
        int i =0;
        String Address = SAddressF.getText();
        String NPassword = SPasswordF.getText();
        String CPassword = SCnfPasswordF.getText();
        String OPassword = SOldPasswordF.getText();
        String  Password1 = null; 
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpd", "root", "Tyagi67@#");
            PreparedStatement ps = con.prepareStatement("select * from customerlogin where Username = '"+Username+"'");
            PreparedStatement ps1 = con.prepareStatement("update customerlogin set Address =?, Password=?, Cnfpwd=? where AccountNumber=?");
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {
                Password1 = rs.getString("Password");
            }
            if(OPassword.equals(Password1))
            {
                if(NPassword.equals(CPassword))
                {
                ps1.setString(1, Address);
                ps1.setString(2, NPassword);
                ps1.setString(3, CPassword);
                ps1.setString(4, accNo);
                i = ps1.executeUpdate();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Password and Confirm Password are not same! Please Try again!");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Old Password is wrong! Please Try again!");
            }
            
             if(i == 1)
             {
                 JOptionPane.showMessageDialog(rootPane,"Details are Successfuly Updated");
                 SAddressF.setText("");
                 SOldPasswordF.setText("");
                 SPasswordF.setText("");
                 SCnfPasswordF.setText("");
             }
             else
             {
                 JOptionPane.showMessageDialog(rootPane,"Some Error Occur");
             }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_SUpdateBActionPerformed

    private void ProfilePComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ProfilePComponentShown
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpd", "root", "Tyagi67@#");
            PreparedStatement ps = con.prepareStatement("select * from customerlogin where Username ='"+Username+"'");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                image = rs.getBytes("ProfilePic");
                username = rs.getString("Username");
                accNo = rs.getString("AccountNumber");
                fname = rs.getString("Fullname");
                email = rs.getString("Email");
                phone = rs.getString("Mobile");
                state = rs.getString("State");
                address = rs.getString("Address");
                district = rs.getString("District");
                pincode = rs.getString("Pincode");
                country = rs.getString("Country");
                acctype = rs.getString("AccType");  
            }
            ImageIcon format = new ImageIcon(image);
            Image mm = format.getImage();
            Image img2 = mm.getScaledInstance(ProfilePic.getWidth(), ProfilePic.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon image = new ImageIcon(img2);
            
            ProfilePic.setIcon(image);
            PUsername.setText(username.toUpperCase());
            PAccountNo.setText(accNo);
            PName.setText(fname.toUpperCase());
            PEmail.setText(email.toUpperCase());
            PPhone.setText(phone);
            PAddress.setText(address.toUpperCase() + ", DISTRICT " + district.toUpperCase() + ", (" + pincode + ")");
            PState.setText(state.toUpperCase());
            PCountry.setText(country.toUpperCase());
            PAccType.setText(acctype);
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_ProfilePComponentShown

    private void DepositePComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DepositePComponentShown
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpd", "root", "Tyagi67@#");
            PreparedStatement ps = con.prepareStatement("select * from customerlogin where Username ='"+Username+"'");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                balance = rs.getString("Balance");
            }
            String string = "\u20B9";
            byte[] utf8 = string.getBytes("UTF-8");
            string = new String(utf8, "UTF-8");
            DCurrentBalL.setText(string + " " + balance);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_DepositePComponentShown

    private void WithdrawPComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_WithdrawPComponentShown
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpd", "root", "Tyagi67@#");
            PreparedStatement ps = con.prepareStatement("select * from customerlogin where Username ='"+Username+"'");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                balance = rs.getString("Balance");
            }
            String string = "\u20B9";
            byte[] utf8 = string.getBytes("UTF-8");
            string = new String(utf8, "UTF-8");
            WCurrentBalL.setText(string + " " + balance);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_WithdrawPComponentShown

    private void TransferPComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_TransferPComponentShown
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpd", "root", "Tyagi67@#");
            PreparedStatement ps = con.prepareStatement("select * from customerlogin where Username ='"+Username+"'");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                balance = rs.getString("Balance");
            }
            String string = "\u20B9";
            byte[] utf8 = string.getBytes("UTF-8");
            string = new String(utf8, "UTF-8");
            TCurrentBalL.setText(string + " " + balance);
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_TransferPComponentShown

    private void SDownloadBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SDownloadBActionPerformed
        MessageFormat header = new MessageFormat("Statement of Account " + accNo + " till today");
        MessageFormat footer = new MessageFormat("page{0,number,integer}");
        try{
            StatementT.print(JTable.PrintMode.FIT_WIDTH,header,footer);
            JOptionPane.showMessageDialog(this,"Statement Generated");
             
        }
        catch(Exception e){
            
        }
        
    }//GEN-LAST:event_SDownloadBActionPerformed

    private void StatementPComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_StatementPComponentShown
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpd", "root", "Tyagi67@#");
            PreparedStatement ps = con.prepareStatement("select AccountNumber from customerlogin where Username ='"+Username+"'");
            PreparedStatement ps1 = con.prepareStatement("select Date, Credit, Debit, ClearBalance from transactions where AccountNumber ='"+accNo+"'");
            ResultSet rs = ps.executeQuery();
            ResultSet rs1 = ps1.executeQuery();
            while(rs.next()){
                accNo = rs.getString("AccountNumber");
            }
            StatementT.setModel(DbUtils.resultSetToTableModel(rs1));
            SAccountNo.setText(accNo);
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_StatementPComponentShown

    private void SettingPComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_SettingPComponentShown
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpd", "root", "Tyagi67@#");
            PreparedStatement ps = con.prepareStatement("select * from customerlogin where Username ='"+Username+"'");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                fname = rs.getString("Fullname");
                email = rs.getString("Email");
                phone = rs.getString("Mobile");
                address = rs.getString("Address");
            }
            SNameL.setText( fname);
            SEmailL.setText( email);
            SPhoneL.setText( phone);
            SAddressF.setText( address);
        }   
       catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_SettingPComponentShown

    
    
    
        private void setColor(JPanel pane) {
        pane.setBackground(new Color(188,167,251));
    }

    private void resetColor(JPanel[] pane, JPanel[] indicators) {
        for (int i = 0; i < pane.length; i++) {
            pane[i].setBackground(new Color(5, 27, 70));

        }
        for (int i = 0; i < indicators.length; i++) {
            indicators[i].setOpaque(false);
        }

    }
    
    
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerMain(Username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane CMainToggel;
    private javax.swing.JButton CheckBalB;
    private javax.swing.JLabel CheckBalL;
    private javax.swing.JPanel CheckBalNav;
    private javax.swing.JTabbedPane CheckBalP;
    private javax.swing.JTextField DAmountF;
    private javax.swing.JLabel DCurrentBalL;
    private javax.swing.JButton DepositB;
    private javax.swing.JPanel DepositeMonNav;
    private javax.swing.JTabbedPane DepositeP;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel PAccType;
    private javax.swing.JLabel PAccountNo;
    private javax.swing.JTextArea PAddress;
    private javax.swing.JLabel PCountry;
    private javax.swing.JLabel PEmail;
    private javax.swing.JButton PGetStatementB;
    private javax.swing.JLabel PName;
    private javax.swing.JLabel PPhone;
    private javax.swing.JLabel PState;
    private javax.swing.JLabel PUsername;
    private javax.swing.JPanel Profile;
    private javax.swing.JPanel ProfileNav;
    private javax.swing.JTabbedPane ProfileP;
    private javax.swing.JLabel ProfilePic;
    private javax.swing.JLabel SAccountNo;
    private javax.swing.JTextArea SAddressF;
    private javax.swing.JPasswordField SCnfPasswordF;
    private javax.swing.JButton SDownloadB;
    private javax.swing.JLabel SEmailL;
    private javax.swing.JLabel SNameL;
    private javax.swing.JPasswordField SOldPasswordF;
    private javax.swing.JPasswordField SPasswordF;
    private javax.swing.JLabel SPhoneL;
    private javax.swing.JButton SUpdateB;
    private javax.swing.JPanel SettingNav;
    private javax.swing.JTabbedPane SettingP;
    private javax.swing.JTabbedPane StatementP;
    private javax.swing.JTable StatementT;
    private javax.swing.JTextField TAmountF;
    private javax.swing.JLabel TCurrentBalL;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel Titlebar;
    private javax.swing.JTextField ToAccountF;
    private javax.swing.JButton TransferB;
    private javax.swing.JPanel TransferMonNav;
    private javax.swing.JTabbedPane TransferP;
    private javax.swing.JTextField WAmountF;
    private javax.swing.JLabel WCurrentBalL;
    private javax.swing.JButton WithdrawB;
    private javax.swing.JPanel WithdrawMonNav;
    private javax.swing.JTabbedPane WithdrawP;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JPanel ind_5;
    private javax.swing.JPanel ind_6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logout;
    // End of variables declaration//GEN-END:variables
}
