/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moneybank;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author tyagi
 */
public class Home1 extends javax.swing.JFrame {

    
    int positionX = 0, positionY = 0;
    
    public Home1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TitleBar = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        ManagerNav = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        CustomerNav = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        HomeToggel = new javax.swing.JTabbedPane();
        ManagerP = new javax.swing.JTabbedPane();
        ManagerLogin = new javax.swing.JPanel();
        MLoginB = new javax.swing.JButton();
        MLUsername = new javax.swing.JTextField();
        MLPassword = new javax.swing.JPasswordField();
        MLoginLabel = new javax.swing.JLabel();
        CustomerP = new javax.swing.JTabbedPane();
        CustomerLogin = new javax.swing.JPanel();
        CLoginB = new javax.swing.JButton();
        CLUsername = new javax.swing.JTextField();
        CLPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        TitleBar.setBackground(new java.awt.Color(23, 35, 51));
        TitleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TitleBarMouseDragged(evt);
            }
        });
        TitleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TitleBarMousePressed(evt);
            }
        });
        TitleBar.setLayout(null);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneybank/images/delete_32px.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        TitleBar.add(Exit);
        Exit.setBounds(1570, 0, 41, 40);

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(188, 167, 251));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Online Banking MoneyApp");
        TitleBar.add(jLabel2);
        jLabel2.setBounds(0, 0, 1570, 40);

        jPanel1.add(TitleBar);
        TitleBar.setBounds(0, 0, 1610, 40);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        ind_1.setBackground(new java.awt.Color(188, 167, 251));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        jPanel3.add(ind_1);
        ind_1.setBounds(0, 330, 10, 85);

        ManagerNav.setBackground(new java.awt.Color(163, 186, 255));
        ManagerNav.setOpaque(false);
        ManagerNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ManagerNavMousePressed(evt);
            }
        });
        ManagerNav.setLayout(null);
        jPanel3.add(ManagerNav);
        ManagerNav.setBounds(10, 330, 300, 85);

        ind_2.setBackground(new java.awt.Color(5, 27, 70));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        jPanel3.add(ind_2);
        ind_2.setBounds(0, 415, 10, 85);

        CustomerNav.setBackground(new java.awt.Color(163, 186, 255));
        CustomerNav.setOpaque(false);
        CustomerNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CustomerNavMousePressed(evt);
            }
        });
        CustomerNav.setLayout(null);
        jPanel3.add(CustomerNav);
        CustomerNav.setBounds(10, 415, 300, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneybank/images/Home-NAV3.png"))); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 310, 770);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 40, 310, 780);

        ManagerLogin.setLayout(null);

        MLoginB.setBorder(null);
        MLoginB.setBorderPainted(false);
        MLoginB.setContentAreaFilled(false);
        MLoginB.setOpaque(false);
        MLoginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MLoginBActionPerformed(evt);
            }
        });
        ManagerLogin.add(MLoginB);
        MLoginB.setBounds(700, 530, 280, 80);

        MLUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MLUsername.setBorder(null);
        MLUsername.setOpaque(false);
        ManagerLogin.add(MLUsername);
        MLUsername.setBounds(710, 282, 300, 50);

        MLPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MLPassword.setBorder(null);
        MLPassword.setOpaque(false);
        ManagerLogin.add(MLPassword);
        MLPassword.setBounds(710, 382, 300, 40);

        MLoginLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneybank/images/home-MLoginWin.png"))); // NOI18N
        ManagerLogin.add(MLoginLabel);
        MLoginLabel.setBounds(0, 0, 1300, 780);

        ManagerP.addTab("tab1", ManagerLogin);

        HomeToggel.addTab("", ManagerP);

        CustomerLogin.setLayout(null);

        CLoginB.setBorder(null);
        CLoginB.setBorderPainted(false);
        CLoginB.setContentAreaFilled(false);
        CLoginB.setOpaque(false);
        CLoginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLoginBActionPerformed(evt);
            }
        });
        CustomerLogin.add(CLoginB);
        CLoginB.setBounds(700, 530, 280, 80);

        CLUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CLUsername.setBorder(null);
        CLUsername.setOpaque(false);
        CustomerLogin.add(CLUsername);
        CLUsername.setBounds(710, 282, 300, 50);

        CLPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CLPassword.setBorder(null);
        CLPassword.setOpaque(false);
        CustomerLogin.add(CLPassword);
        CLPassword.setBounds(710, 380, 300, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneybank/images/home-CLoginWin.png"))); // NOI18N
        CustomerLogin.add(jLabel4);
        jLabel4.setBounds(0, 0, 1300, 780);

        CustomerP.addTab("tab1", CustomerLogin);

        HomeToggel.addTab("", CustomerP);

        jPanel1.add(HomeToggel);
        HomeToggel.setBounds(310, -20, 1300, 830);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1611, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void TitleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleBarMousePressed
        positionX = evt.getX();
        positionY = evt.getY();
    }//GEN-LAST:event_TitleBarMousePressed

    private void TitleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleBarMouseDragged
        setLocation(evt.getXOnScreen() - positionX, evt.getYOnScreen() - positionY);
    }//GEN-LAST:event_TitleBarMouseDragged

    private void ManagerNavMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManagerNavMousePressed
        setColor(ind_1);
        resetColor(new JPanel[]{ind_2}, new JPanel[]{CustomerNav});
        HomeToggel.setSelectedIndex(0);
    }//GEN-LAST:event_ManagerNavMousePressed

    private void CustomerNavMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerNavMousePressed
        setColor(ind_2);
        resetColor(new JPanel[]{ind_1}, new JPanel[]{ManagerNav});
        HomeToggel.setSelectedIndex(1);
    }//GEN-LAST:event_CustomerNavMousePressed

    private void MLoginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MLoginBActionPerformed
        String Username = MLUsername.getText();
        String Password = MLPassword.getText();
        String Username1 = null, Password1 = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpd", "root", "Tyagi67@#");
            PreparedStatement ps = con.prepareStatement("select * from managerlogin where Username = '"+Username+"'");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Username1 = rs.getString("Username");
                Password1 = rs.getString("Password");
            }
            if (Password.equals(Password1) && Username.equals(Username1)) {
                ManagerMain mm = new ManagerMain(Username1);
                mm.setVisible(true);
                setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Username or Password is wrong! Please Try again!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_MLoginBActionPerformed

    private void CLoginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLoginBActionPerformed
        String Username = CLUsername.getText();
        String Password = CLPassword.getText();
        String Username1 = null, Password1 = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpd", "root", "Tyagi67@#");
            PreparedStatement ps = con.prepareStatement("select * from customerlogin where Username = '"+Username+"'");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Username1 = rs.getString("Username");
                Password1 = rs.getString("Password");
            }
            if (Password.equals(Password1) && Username.equals(Username1)) {
                CustomerMain cm = new CustomerMain(Username);
                cm.setVisible(true);
                setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Username or Password is wrong! Please Try again!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_CLoginBActionPerformed

    
    
    
    
    
    
    private void setColor(JPanel pane) {
        pane.setBackground(new Color(188,167,251));
    }

    private void resetColor(JPanel[] pane, JPanel[] indicators) {
        for (int i = 0; i < pane.length; i++) {
            pane[i].setBackground(new Color(5, 27, 70));

        }
        for (int i = 0; i < indicators.length; i++) {
            indicators[i].setOpaque(false);
        }

    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CLPassword;
    private javax.swing.JTextField CLUsername;
    private javax.swing.JButton CLoginB;
    private javax.swing.JPanel CustomerLogin;
    private javax.swing.JPanel CustomerNav;
    private javax.swing.JTabbedPane CustomerP;
    private javax.swing.JLabel Exit;
    private javax.swing.JTabbedPane HomeToggel;
    private javax.swing.JPasswordField MLPassword;
    private javax.swing.JTextField MLUsername;
    private javax.swing.JButton MLoginB;
    private javax.swing.JLabel MLoginLabel;
    private javax.swing.JPanel ManagerLogin;
    private javax.swing.JPanel ManagerNav;
    private javax.swing.JTabbedPane ManagerP;
    private javax.swing.JPanel TitleBar;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
