/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moneybank;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JFileChooser;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.text.MessageFormat;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JTable;
import static moneybank.CustomerMain.Username;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author tyagi
 */
public class ManagerMain extends javax.swing.JFrame {

    static String Username;
    int positionX = 0, positionY = 0;
    byte[ ] image = null;
    byte[] person_image = null;
    int rowCount = 0;
    String filename = null;
    int cBal, nBal, tBal, MinB;
    String username= null,email = null, pwd = null, balance = null, accNo = null,fname = null,phone = null,district = null,pincode = null,cnfpwd = null, address = null, country = null, loanacc=null, empid = null,branch = null, designation = null;
    String state = null, minb = "0", toAcc = null, toAccBal = null, gender = null, acctype = null;
    String timeStamp = new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss").format(new java.util.Date());
    public ManagerMain(String Username) {
        this.Username = Username;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titlebar = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        MProfileNav = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        AddCustomerNav = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        UpdateCNav = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        ViewTransactionNav = new javax.swing.JPanel();
        ind_5 = new javax.swing.JPanel();
        ViewCustomerList = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CMainToggel = new javax.swing.JTabbedPane();
        MProfileP = new javax.swing.JTabbedPane();
        Profile = new javax.swing.JPanel();
        MPProfilePic = new javax.swing.JLabel();
        MPUsername = new javax.swing.JLabel();
        MPEmpId = new javax.swing.JLabel();
        MPName = new javax.swing.JLabel();
        MPEmail = new javax.swing.JLabel();
        MPPhone = new javax.swing.JLabel();
        MPAddress = new javax.swing.JTextArea();
        MPGender = new javax.swing.JLabel();
        MPBranch = new javax.swing.JLabel();
        MPDesignation = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        AddCustomer = new javax.swing.JTabbedPane();
        AddCustomerSP = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        MAccountNo = new javax.swing.JLabel();
        MFullname = new javax.swing.JTextField();
        MEmail = new javax.swing.JTextField();
        MPhone = new javax.swing.JTextField();
        MGender = new javax.swing.JTextField();
        MAddress = new javax.swing.JTextArea();
        MState = new javax.swing.JTextField();
        MDistrict = new javax.swing.JTextField();
        MCountry = new javax.swing.JTextField();
        MPincode = new javax.swing.JTextField();
        MAccType = new javax.swing.JComboBox<>();
        MUsername = new javax.swing.JTextField();
        MUploadB = new javax.swing.JButton();
        MProfilePic = new javax.swing.JTextField();
        MPassword = new javax.swing.JPasswordField();
        MCPassword = new javax.swing.JPasswordField();
        MBalance = new javax.swing.JTextField();
        MAddUserB = new javax.swing.JButton();
        UpdateCustomer = new javax.swing.JTabbedPane();
        UpdateCustomerSP = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        UUsernameSF = new javax.swing.JTextField();
        UAccountNoSF = new javax.swing.JTextField();
        USearchB = new javax.swing.JButton();
        UAccountNo = new javax.swing.JLabel();
        UFullname = new javax.swing.JTextField();
        UEmail = new javax.swing.JTextField();
        UPhone = new javax.swing.JTextField();
        UGender = new javax.swing.JTextField();
        UAddress = new javax.swing.JTextArea();
        UState = new javax.swing.JTextField();
        UDistrict = new javax.swing.JTextField();
        UCountry = new javax.swing.JTextField();
        UPincode = new javax.swing.JTextField();
        UAccType = new javax.swing.JComboBox<>();
        UUsername = new javax.swing.JTextField();
        UPicUpload = new javax.swing.JButton();
        UProfilePic = new javax.swing.JTextField();
        UPassword = new javax.swing.JPasswordField();
        UCPassword = new javax.swing.JPasswordField();
        UBalance = new javax.swing.JTextField();
        UUpadateB = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ViewTransacton = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        MTransactionT = new javax.swing.JScrollPane();
        ATStatement = new javax.swing.JTable();
        ATPrintB = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ViewCustomerDetail = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Customerlist = new javax.swing.JTable();
        CLPrintB = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        Titlebar.setBackground(new java.awt.Color(23, 35, 51));
        Titlebar.setLayout(null);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneybank/images/delete_32px.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        Titlebar.add(Exit);
        Exit.setBounds(1570, 0, 41, 40);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneybank/images/newlogout.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        Titlebar.add(logout);
        logout.setBounds(1530, 0, 40, 40);

        Title.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(188, 167, 251));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Online Banking MoneyApp");
        Titlebar.add(Title);
        Title.setBounds(0, 0, 1570, 40);

        jPanel1.add(Titlebar);
        Titlebar.setBounds(0, 0, 1610, 40);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        ind_1.setBackground(new java.awt.Color(188, 167, 251));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel3.add(ind_1);
        ind_1.setBounds(0, 250, 10, 80);

        MProfileNav.setBackground(new java.awt.Color(163, 186, 255));
        MProfileNav.setOpaque(false);
        MProfileNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MProfileNavMousePressed(evt);
            }
        });
        MProfileNav.setLayout(null);
        jPanel3.add(MProfileNav);
        MProfileNav.setBounds(10, 250, 300, 80);

        ind_2.setBackground(new java.awt.Color(5, 27, 70));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel3.add(ind_2);
        ind_2.setBounds(0, 330, 10, 80);

        AddCustomerNav.setBackground(new java.awt.Color(163, 186, 255));
        AddCustomerNav.setOpaque(false);
        AddCustomerNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AddCustomerNavMousePressed(evt);
            }
        });
        AddCustomerNav.setLayout(null);
        jPanel3.add(AddCustomerNav);
        AddCustomerNav.setBounds(10, 330, 300, 80);

        ind_3.setBackground(new java.awt.Color(5, 27, 70));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        jPanel3.add(ind_3);
        ind_3.setBounds(0, 410, 10, 75);

        UpdateCNav.setBackground(new java.awt.Color(163, 186, 255));
        UpdateCNav.setOpaque(false);
        UpdateCNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UpdateCNavMousePressed(evt);
            }
        });
        UpdateCNav.setLayout(null);
        jPanel3.add(UpdateCNav);
        UpdateCNav.setBounds(10, 410, 300, 75);

        ind_4.setBackground(new java.awt.Color(5, 27, 70));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        jPanel3.add(ind_4);
        ind_4.setBounds(0, 485, 10, 75);

        ViewTransactionNav.setBackground(new java.awt.Color(163, 186, 255));
        ViewTransactionNav.setOpaque(false);
        ViewTransactionNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ViewTransactionNavMousePressed(evt);
            }
        });
        ViewTransactionNav.setLayout(null);
        jPanel3.add(ViewTransactionNav);
        ViewTransactionNav.setBounds(10, 485, 300, 75);

        ind_5.setBackground(new java.awt.Color(5, 27, 70));

        javax.swing.GroupLayout ind_5Layout = new javax.swing.GroupLayout(ind_5);
        ind_5.setLayout(ind_5Layout);
        ind_5Layout.setHorizontalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ind_5Layout.setVerticalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        jPanel3.add(ind_5);
        ind_5.setBounds(0, 560, 10, 75);

        ViewCustomerList.setBackground(new java.awt.Color(163, 186, 255));
        ViewCustomerList.setOpaque(false);
        ViewCustomerList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ViewCustomerListMousePressed(evt);
            }
        });
        ViewCustomerList.setLayout(null);
        jPanel3.add(ViewCustomerList);
        ViewCustomerList.setBounds(10, 560, 300, 75);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneybank/images/Manager NAV.png"))); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, -10, 320, 780);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 40, 310, 780);

        CMainToggel.setEnabled(false);
        CMainToggel.setFocusable(false);
        CMainToggel.setRequestFocusEnabled(false);
        CMainToggel.setVerifyInputWhenFocusTarget(false);

        MProfileP.setEnabled(false);
        MProfileP.setFocusable(false);
        MProfileP.setRequestFocusEnabled(false);
        MProfileP.setVerifyInputWhenFocusTarget(false);
        MProfileP.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                MProfilePComponentShown(evt);
            }
        });

        Profile.setEnabled(false);
        Profile.setOpaque(false);
        Profile.setRequestFocusEnabled(false);
        Profile.setVerifyInputWhenFocusTarget(false);
        Profile.setLayout(null);
        Profile.add(MPProfilePic);
        MPProfilePic.setBounds(560, 40, 180, 160);

        MPUsername.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        MPUsername.setForeground(new java.awt.Color(255, 102, 102));
        MPUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Profile.add(MPUsername);
        MPUsername.setBounds(510, 215, 283, 50);

        MPEmpId.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        MPEmpId.setForeground(new java.awt.Color(204, 204, 255));
        MPEmpId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Profile.add(MPEmpId);
        MPEmpId.setBounds(290, 318, 310, 35);

        MPName.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        MPName.setForeground(new java.awt.Color(204, 204, 255));
        MPName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Profile.add(MPName);
        MPName.setBounds(898, 318, 310, 35);

        MPEmail.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        MPEmail.setForeground(new java.awt.Color(204, 204, 255));
        MPEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Profile.add(MPEmail);
        MPEmail.setBounds(290, 395, 310, 35);

        MPPhone.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        MPPhone.setForeground(new java.awt.Color(204, 204, 255));
        MPPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Profile.add(MPPhone);
        MPPhone.setBounds(898, 395, 310, 35);

        MPAddress.setEditable(false);
        MPAddress.setBackground(new java.awt.Color(90, 102, 123));
        MPAddress.setColumns(20);
        MPAddress.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        MPAddress.setForeground(new java.awt.Color(255, 255, 255));
        MPAddress.setLineWrap(true);
        MPAddress.setRows(5);
        MPAddress.setWrapStyleWord(true);
        MPAddress.setFocusable(false);
        MPAddress.setOpaque(false);
        MPAddress.setRequestFocusEnabled(false);
        MPAddress.setVerifyInputWhenFocusTarget(false);
        Profile.add(MPAddress);
        MPAddress.setBounds(900, 480, 310, 180);

        MPGender.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        MPGender.setForeground(new java.awt.Color(204, 204, 255));
        MPGender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Profile.add(MPGender);
        MPGender.setBounds(290, 473, 310, 35);

        MPBranch.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        MPBranch.setForeground(new java.awt.Color(204, 204, 255));
        MPBranch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Profile.add(MPBranch);
        MPBranch.setBounds(290, 552, 310, 35);

        MPDesignation.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        MPDesignation.setForeground(new java.awt.Color(204, 204, 255));
        MPDesignation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Profile.add(MPDesignation);
        MPDesignation.setBounds(290, 632, 310, 35);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneybank/images/empProfile.png"))); // NOI18N
        Profile.add(jLabel8);
        jLabel8.setBounds(0, 0, 1300, 780);

        MProfileP.addTab("tab1", Profile);

        CMainToggel.addTab("", MProfileP);

        AddCustomer.setEnabled(false);
        AddCustomer.setRequestFocusEnabled(false);
        AddCustomer.setVerifyInputWhenFocusTarget(false);
        AddCustomer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                AddCustomerComponentShown(evt);
            }
        });

        AddCustomerSP.setBorder(null);
        AddCustomerSP.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        AddCustomerSP.setEnabled(false);
        AddCustomerSP.setFocusable(false);
        AddCustomerSP.setOpaque(false);
        AddCustomerSP.setRequestFocusEnabled(false);
        AddCustomerSP.setVerifyInputWhenFocusTarget(false);

        jPanel8.setDoubleBuffered(false);
        jPanel8.setEnabled(false);
        jPanel8.setFocusable(false);
        jPanel8.setOpaque(false);
        jPanel8.setRequestFocusEnabled(false);
        jPanel8.setVerifyInputWhenFocusTarget(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneybank/images/AddUser.png"))); // NOI18N
        jLabel7.setOpaque(true);

        MAccountNo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MAccountNo.setForeground(new java.awt.Color(255, 102, 102));
        MAccountNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MAccountNo.setFocusCycleRoot(true);
        MAccountNo.setFocusTraversalPolicyProvider(true);

        MFullname.setBackground(new java.awt.Color(90, 102, 123));
        MFullname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MFullname.setForeground(new java.awt.Color(255, 255, 255));
        MFullname.setAutoscrolls(false);
        MFullname.setBorder(null);
        MFullname.setOpaque(false);

        MEmail.setBackground(new java.awt.Color(90, 102, 123));
        MEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MEmail.setForeground(new java.awt.Color(255, 255, 255));
        MEmail.setAutoscrolls(false);
        MEmail.setBorder(null);
        MEmail.setOpaque(false);

        MPhone.setBackground(new java.awt.Color(90, 102, 123));
        MPhone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MPhone.setForeground(new java.awt.Color(255, 255, 255));
        MPhone.setAutoscrolls(false);
        MPhone.setBorder(null);
        MPhone.setOpaque(false);

        MGender.setBackground(new java.awt.Color(90, 102, 123));
        MGender.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MGender.setForeground(new java.awt.Color(255, 255, 255));
        MGender.setAutoscrolls(false);
        MGender.setBorder(null);
        MGender.setOpaque(false);

        MAddress.setBackground(new java.awt.Color(90, 102, 123));
        MAddress.setColumns(20);
        MAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MAddress.setForeground(new java.awt.Color(255, 255, 255));
        MAddress.setLineWrap(true);
        MAddress.setRows(5);
        MAddress.setWrapStyleWord(true);
        MAddress.setAutoscrolls(false);
        MAddress.setOpaque(false);

        MState.setBackground(new java.awt.Color(90, 102, 123));
        MState.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MState.setForeground(new java.awt.Color(255, 255, 255));
        MState.setAutoscrolls(false);
        MState.setBorder(null);
        MState.setOpaque(false);

        MDistrict.setBackground(new java.awt.Color(90, 102, 123));
        MDistrict.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MDistrict.setForeground(new java.awt.Color(255, 255, 255));
        MDistrict.setAutoscrolls(false);
        MDistrict.setBorder(null);
        MDistrict.setOpaque(false);

        MCountry.setBackground(new java.awt.Color(90, 102, 123));
        MCountry.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MCountry.setForeground(new java.awt.Color(255, 255, 255));
        MCountry.setAutoscrolls(false);
        MCountry.setBorder(null);
        MCountry.setOpaque(false);

        MPincode.setBackground(new java.awt.Color(90, 102, 123));
        MPincode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MPincode.setForeground(new java.awt.Color(255, 255, 255));
        MPincode.setAutoscrolls(false);
        MPincode.setBorder(null);
        MPincode.setOpaque(false);

        MAccType.setBackground(new java.awt.Color(90, 102, 123));
        MAccType.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MAccType.setForeground(new java.awt.Color(255, 255, 255));
        MAccType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select>", "Saving", "Current" }));
        MAccType.setFocusable(false);
        MAccType.setOpaque(false);

        MUsername.setBackground(new java.awt.Color(90, 102, 123));
        MUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MUsername.setForeground(new java.awt.Color(255, 255, 255));
        MUsername.setAutoscrolls(false);
        MUsername.setBorder(null);
        MUsername.setOpaque(false);

        MUploadB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MUploadB.setForeground(new java.awt.Color(255, 255, 255));
        MUploadB.setBorder(null);
        MUploadB.setContentAreaFilled(false);
        MUploadB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MUploadBActionPerformed(evt);
            }
        });

        MProfilePic.setEditable(false);
        MProfilePic.setBackground(new java.awt.Color(90, 102, 123));
        MProfilePic.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MProfilePic.setForeground(new java.awt.Color(255, 255, 255));
        MProfilePic.setAutoscrolls(false);
        MProfilePic.setBorder(null);
        MProfilePic.setOpaque(false);

        MPassword.setBackground(new java.awt.Color(90, 102, 123));
        MPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MPassword.setForeground(new java.awt.Color(255, 255, 255));
        MPassword.setAutoscrolls(false);
        MPassword.setBorder(null);
        MPassword.setOpaque(false);

        MCPassword.setBackground(new java.awt.Color(90, 102, 123));
        MCPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MCPassword.setForeground(new java.awt.Color(255, 255, 255));
        MCPassword.setAutoscrolls(false);
        MCPassword.setBorder(null);
        MCPassword.setOpaque(false);

        MBalance.setBackground(new java.awt.Color(90, 102, 123));
        MBalance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MBalance.setForeground(new java.awt.Color(255, 255, 255));
        MBalance.setAutoscrolls(false);
        MBalance.setBorder(null);
        MBalance.setOpaque(false);

        MAddUserB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MAddUserB.setForeground(new java.awt.Color(255, 255, 255));
        MAddUserB.setBorder(null);
        MAddUserB.setContentAreaFilled(false);
        MAddUserB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAddUserBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(277, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(MAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(282, 282, 282)
                        .addComponent(MFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(MEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(282, 282, 282)
                        .addComponent(MPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MGender, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MState, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(282, 282, 282)
                        .addComponent(MAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(MCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(282, 282, 282)
                        .addComponent(MPincode, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(MAccType, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(278, 278, 278)
                        .addComponent(MUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(MUploadB, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(277, 277, 277)
                        .addComponent(MPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(MCPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(282, 282, 282)
                        .addComponent(MBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(MAddUserB, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(114, 114, 114))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1323, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                    .addContainerGap(280, Short.MAX_VALUE)
                    .addComponent(MProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(906, 906, 906)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(MGender, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(MState, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(MDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(MAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MPincode, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MAccType, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MUploadB, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MCPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(MAddUserB, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                    .addContainerGap(812, Short.MAX_VALUE)
                    .addComponent(MProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(246, 246, 246)))
        );

        AddCustomerSP.setViewportView(jPanel8);

        AddCustomer.addTab("", AddCustomerSP);

        CMainToggel.addTab("", AddCustomer);

        UpdateCustomer.setEnabled(false);
        UpdateCustomer.setFocusable(false);
        UpdateCustomer.setRequestFocusEnabled(false);
        UpdateCustomer.setVerifyInputWhenFocusTarget(false);

        UpdateCustomerSP.setBorder(null);
        UpdateCustomerSP.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        UpdateCustomerSP.setEnabled(false);
        UpdateCustomerSP.setFocusable(false);
        UpdateCustomerSP.setOpaque(false);
        UpdateCustomerSP.setRequestFocusEnabled(false);
        UpdateCustomerSP.setVerifyInputWhenFocusTarget(false);

        jPanel9.setDoubleBuffered(false);
        jPanel9.setEnabled(false);
        jPanel9.setFocusable(false);
        jPanel9.setOpaque(false);
        jPanel9.setRequestFocusEnabled(false);
        jPanel9.setVerifyInputWhenFocusTarget(false);
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UUsernameSF.setBackground(new java.awt.Color(90, 102, 123));
        UUsernameSF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UUsernameSF.setForeground(new java.awt.Color(255, 255, 255));
        UUsernameSF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UUsernameSF.setText("Username");
        UUsernameSF.setBorder(null);
        UUsernameSF.setOpaque(false);
        UUsernameSF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UUsernameSFFocusGained(evt);
            }
        });
        jPanel9.add(UUsernameSF, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 25, 212, 40));

        UAccountNoSF.setBackground(new java.awt.Color(90, 102, 123));
        UAccountNoSF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UAccountNoSF.setForeground(new java.awt.Color(255, 255, 255));
        UAccountNoSF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UAccountNoSF.setText("Account No.");
        UAccountNoSF.setBorder(null);
        UAccountNoSF.setOpaque(false);
        UAccountNoSF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UAccountNoSFFocusGained(evt);
            }
        });
        jPanel9.add(UAccountNoSF, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 109, 212, 40));

        USearchB.setForeground(new java.awt.Color(255, 255, 255));
        USearchB.setBorder(null);
        USearchB.setContentAreaFilled(false);
        USearchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USearchBActionPerformed(evt);
            }
        });
        jPanel9.add(USearchB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1153, 68, 108, 41));

        UAccountNo.setBackground(new java.awt.Color(90, 102, 123));
        UAccountNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UAccountNo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.add(UAccountNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 219, 315, 43));

        UFullname.setBackground(new java.awt.Color(90, 102, 123));
        UFullname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UFullname.setForeground(new java.awt.Color(255, 255, 255));
        UFullname.setBorder(null);
        UFullname.setOpaque(false);
        jPanel9.add(UFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 219, 315, 43));

        UEmail.setBackground(new java.awt.Color(90, 102, 123));
        UEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UEmail.setForeground(new java.awt.Color(255, 255, 255));
        UEmail.setBorder(null);
        UEmail.setOpaque(false);
        jPanel9.add(UEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 306, 315, 41));

        UPhone.setBackground(new java.awt.Color(90, 102, 123));
        UPhone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UPhone.setForeground(new java.awt.Color(255, 255, 255));
        UPhone.setBorder(null);
        UPhone.setOpaque(false);
        jPanel9.add(UPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 306, 315, 41));

        UGender.setBackground(new java.awt.Color(90, 102, 123));
        UGender.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UGender.setForeground(new java.awt.Color(255, 255, 255));
        UGender.setBorder(null);
        UGender.setOpaque(false);
        jPanel9.add(UGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 393, 315, 41));

        UAddress.setBackground(new java.awt.Color(90, 102, 123));
        UAddress.setColumns(20);
        UAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UAddress.setForeground(new java.awt.Color(255, 255, 255));
        UAddress.setLineWrap(true);
        UAddress.setRows(5);
        UAddress.setWrapStyleWord(true);
        UAddress.setOpaque(false);
        jPanel9.add(UAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 404, 315, 200));

        UState.setBackground(new java.awt.Color(90, 102, 123));
        UState.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UState.setForeground(new java.awt.Color(255, 255, 255));
        UState.setBorder(null);
        UState.setOpaque(false);
        jPanel9.add(UState, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 481, 315, 43));

        UDistrict.setBackground(new java.awt.Color(90, 102, 123));
        UDistrict.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UDistrict.setForeground(new java.awt.Color(255, 255, 255));
        UDistrict.setBorder(null);
        UDistrict.setOpaque(false);
        UDistrict.setVerifyInputWhenFocusTarget(false);
        jPanel9.add(UDistrict, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 570, 315, 41));

        UCountry.setBackground(new java.awt.Color(90, 102, 123));
        UCountry.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UCountry.setForeground(new java.awt.Color(255, 255, 255));
        UCountry.setBorder(null);
        UCountry.setOpaque(false);
        jPanel9.add(UCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 657, 315, 41));

        UPincode.setBackground(new java.awt.Color(90, 102, 123));
        UPincode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UPincode.setForeground(new java.awt.Color(255, 255, 255));
        UPincode.setBorder(null);
        UPincode.setOpaque(false);
        jPanel9.add(UPincode, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 657, 315, 41));

        UAccType.setBackground(new java.awt.Color(90, 102, 123));
        UAccType.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UAccType.setForeground(new java.awt.Color(255, 255, 255));
        UAccType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select>", "Saving", "Current" }));
        UAccType.setOpaque(false);
        jPanel9.add(UAccType, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 749, 315, 41));

        UUsername.setBackground(new java.awt.Color(90, 102, 123));
        UUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UUsername.setForeground(new java.awt.Color(255, 255, 255));
        UUsername.setBorder(null);
        UUsername.setOpaque(false);
        jPanel9.add(UUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 749, 315, 41));

        UPicUpload.setForeground(new java.awt.Color(255, 255, 255));
        UPicUpload.setBorder(null);
        UPicUpload.setContentAreaFilled(false);
        UPicUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPicUploadActionPerformed(evt);
            }
        });
        jPanel9.add(UPicUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 837, 332, 41));

        UProfilePic.setEditable(false);
        UProfilePic.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UProfilePic.setForeground(new java.awt.Color(255, 255, 255));
        UProfilePic.setAutoscrolls(false);
        UProfilePic.setBorder(null);
        UProfilePic.setOpaque(false);
        jPanel9.add(UProfilePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        UPassword.setBackground(new java.awt.Color(90, 102, 123));
        UPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UPassword.setForeground(new java.awt.Color(255, 255, 255));
        UPassword.setBorder(null);
        UPassword.setOpaque(false);
        jPanel9.add(UPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 837, 315, 41));

        UCPassword.setBackground(new java.awt.Color(90, 102, 123));
        UCPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UCPassword.setForeground(new java.awt.Color(255, 255, 255));
        UCPassword.setBorder(null);
        UCPassword.setOpaque(false);
        jPanel9.add(UCPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 924, 315, 41));

        UBalance.setBackground(new java.awt.Color(90, 102, 123));
        UBalance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UBalance.setForeground(new java.awt.Color(255, 255, 255));
        UBalance.setBorder(null);
        UBalance.setOpaque(false);
        jPanel9.add(UBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 924, 315, 41));

        UUpadateB.setForeground(new java.awt.Color(255, 255, 255));
        UUpadateB.setBorder(null);
        UUpadateB.setContentAreaFilled(false);
        UUpadateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UUpadateBActionPerformed(evt);
            }
        });
        jPanel9.add(UUpadateB, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 1015, 288, 66));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneybank/images/Update Data.png"))); // NOI18N
        jLabel9.setFocusable(false);
        jLabel9.setInheritsPopupMenu(false);
        jLabel9.setRequestFocusEnabled(false);
        jLabel9.setVerifyInputWhenFocusTarget(false);
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        UpdateCustomerSP.setViewportView(jPanel9);

        UpdateCustomer.addTab("", UpdateCustomerSP);

        CMainToggel.addTab("", UpdateCustomer);

        ViewTransacton.setEnabled(false);
        ViewTransacton.setFocusable(false);
        ViewTransacton.setRequestFocusEnabled(false);
        ViewTransacton.setVerifyInputWhenFocusTarget(false);
        ViewTransacton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ViewTransactonComponentShown(evt);
            }
        });

        jPanel5.setDoubleBuffered(false);
        jPanel5.setEnabled(false);
        jPanel5.setOpaque(false);
        jPanel5.setRequestFocusEnabled(false);
        jPanel5.setVerifyInputWhenFocusTarget(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MTransactionT.setBorder(null);
        MTransactionT.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MTransactionT.setOpaque(false);
        MTransactionT.setRequestFocusEnabled(false);
        MTransactionT.setVerifyInputWhenFocusTarget(false);

        ATStatement.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ATStatement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"c v v bv b b", "vb vb vb ", "v vb bv ", "vb vb vb "},
                {"v v vb ", "vb vb vb", "b vb ", null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1v vb ", "Title 2vb v v", "Title 3vb vb vb", "Title 4 vb vb  "
            }
        ));
        ATStatement.setColumnSelectionAllowed(true);
        ATStatement.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ATStatement.setOpaque(false);
        ATStatement.setRowHeight(45);
        ATStatement.setRowSelectionAllowed(false);
        ATStatement.setUpdateSelectionOnSort(false);
        ATStatement.setVerifyInputWhenFocusTarget(false);
        MTransactionT.setViewportView(ATStatement);

        jPanel5.add(MTransactionT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 1190, 540));

        ATPrintB.setContentAreaFilled(false);
        ATPrintB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATPrintBActionPerformed(evt);
            }
        });
        jPanel5.add(ATPrintB, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 690, 250, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneybank/images/MTransactions.png"))); // NOI18N
        jLabel5.setInheritsPopupMenu(false);
        jLabel5.setRequestFocusEnabled(false);
        jLabel5.setVerifyInputWhenFocusTarget(false);
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        ViewTransacton.addTab("tab1", jPanel5);

        CMainToggel.addTab("", ViewTransacton);

        ViewCustomerDetail.setEnabled(false);
        ViewCustomerDetail.setFocusable(false);
        ViewCustomerDetail.setRequestFocusEnabled(false);
        ViewCustomerDetail.setVerifyInputWhenFocusTarget(false);
        ViewCustomerDetail.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ViewCustomerDetailComponentShown(evt);
            }
        });

        jPanel11.setDoubleBuffered(false);
        jPanel11.setEnabled(false);
        jPanel11.setFocusable(false);
        jPanel11.setOpaque(false);
        jPanel11.setRequestFocusEnabled(false);
        jPanel11.setVerifyInputWhenFocusTarget(false);
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        Customerlist.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Customerlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Customerlist.setRowHeight(40);
        Customerlist.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(Customerlist);

        jPanel11.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 1180, 530));

        CLPrintB.setContentAreaFilled(false);
        CLPrintB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLPrintBActionPerformed(evt);
            }
        });
        jPanel11.add(CLPrintB, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 690, 250, 50));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneybank/images/Customer List.png"))); // NOI18N
        jLabel11.setFocusable(false);
        jLabel11.setInheritsPopupMenu(false);
        jLabel11.setRequestFocusEnabled(false);
        jLabel11.setVerifyInputWhenFocusTarget(false);
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        ViewCustomerDetail.addTab("tab2", jPanel11);

        CMainToggel.addTab("", ViewCustomerDetail);

        jPanel1.add(CMainToggel);
        CMainToggel.setBounds(310, -20, 1300, 840);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1607, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_ExitMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Home1 hm = new Home1();
        hm.setVisible(true);
        setVisible(false);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void AddCustomerNavMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddCustomerNavMousePressed
        setColor(ind_2);
        resetColor(new JPanel[]{ind_1,ind_3,ind_4,ind_5}, new JPanel[]{MProfileNav,UpdateCNav,ViewTransactionNav,ViewCustomerList});
        CMainToggel.setSelectedIndex(1);
    }//GEN-LAST:event_AddCustomerNavMousePressed

    private void UpdateCNavMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateCNavMousePressed
        setColor(ind_3);
        resetColor(new JPanel[]{ind_2,ind_1,ind_4,ind_5}, new JPanel[]{AddCustomerNav,MProfileNav,ViewTransactionNav,ViewCustomerList});
        CMainToggel.setSelectedIndex(2);
    }//GEN-LAST:event_UpdateCNavMousePressed

    private void ViewTransactionNavMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewTransactionNavMousePressed
        setColor(ind_4);
        resetColor(new JPanel[]{ind_3,ind_2,ind_1,ind_5}, new JPanel[]{UpdateCNav,AddCustomerNav,MProfileNav,ViewCustomerList});
        CMainToggel.setSelectedIndex(3);
    }//GEN-LAST:event_ViewTransactionNavMousePressed

    private void ViewCustomerListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewCustomerListMousePressed
        setColor(ind_5);
        resetColor(new JPanel[]{ind_4,ind_3,ind_2,ind_1}, new JPanel[]{ViewTransactionNav,UpdateCNav,AddCustomerNav,MProfileNav});
        CMainToggel.setSelectedIndex(4);
    }//GEN-LAST:event_ViewCustomerListMousePressed

    private void AddCustomerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_AddCustomerComponentShown
        Random ra = new Random();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpd", "root", "Tyagi67@#");
            PreparedStatement ps = con.prepareStatement("select * from customerlogin");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                rowCount += 1;
            }
            MAccountNo.setText(""+ra.nextInt(5512010+1));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_AddCustomerComponentShown

    private void MAddUserBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAddUserBActionPerformed
        File f = new File(filename);
        int i =0;
        String AccountNumber = MAccountNo.getText();
        String Fullname = MFullname.getText();
        String Email = MEmail.getText();
        String Mobile = MPhone.getText();
        String Gender = MGender.getText();
        String Address = MAddress.getText();
        String State = MState.getText();
        String District = MDistrict.getText();
        String Country = MCountry.getText();
        String Pincode = MPincode.getText();
        String AccType = MAccType.getSelectedItem().toString();
        String Username = MUsername.getText();
        String Image = MProfilePic.getText();
        String Password = String.valueOf(MPassword.getPassword());
        String Cnfpwd = String.valueOf(MCPassword.getPassword());
        String Balance = MBalance.getText();
            try {
            InputStream is = new FileInputStream(f);
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpd", "root", "Tyagi67@#");
           PreparedStatement ps = con.prepareStatement("insert into customerlogin values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                 if (Cnfpwd.equals(Password)) {
                ps.setString(1, AccountNumber);
                ps.setString(2, Fullname);
                ps.setString(3, Email);
                ps.setString(4, Mobile);
                ps.setString(5, Gender);
                ps.setString(6, Address);
                ps.setString(7, State);
                ps.setString(8, District);
                ps.setString(9, Country);
                ps.setString(10, Pincode);
                ps.setString(11,AccType);
                ps.setString(12, Username);
                ps.setBlob(13, is);
                ps.setString(14, Password);
                ps.setString(15, Cnfpwd);
                ps.setString(16,Balance);
                i = ps.executeUpdate();
                System.out.println(i);
            }
            else
            {
                 JOptionPane.showMessageDialog(null, "Please Enter Same Password!");
            }
            if (i == 1) {
            JOptionPane.showMessageDialog(null, "User Added Successfull");
                MAccountNo.setText(" ");
                MFullname.setText(" ");
                MEmail.setText(" ");
                MPhone.setText(" ");
                MGender.setText(" ");
                MAddress.setText(" ");
                MState.setText(" ");
                MDistrict.setText(" ");
                MCountry.setText(" ");
                MPincode.setText(" ");
                MAccType.setSelectedIndex(0);
                MUsername.setText(" ");
                MProfilePic.setText(" ");
                MPassword.setText(" ");
                MCPassword.setText(" ");
                MBalance.setText(" ");
                
            } else {
                JOptionPane.showMessageDialog(null, "Some Error Occured!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_MAddUserBActionPerformed

    private void MUploadBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MUploadBActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        int radius= 40;
        filename = f.getAbsolutePath();
        MProfilePic.setText(filename);
        String PATTERN = "^(([a-zA-Z]:)|(\\\\{2}\\w+)\\$?)(\\\\(\\w[\\w].*))(.jpg|.JPG|.png|.PNG|.jpeg|.JPEG)$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(MProfilePic.getText());
        if (!match.matches()) {
            MProfilePic.setText(" Please Select Image in png only!");
            filename = null;
        } else {
            MProfilePic.setText(null);

            ImageIcon imageicon = new ImageIcon(filename);
            Image img = imageicon.getImage().getScaledInstance(2*radius, 2*radius, Image.SCALE_SMOOTH);
            MProfilePic.setText(filename);

            try {
                File image = new File(filename);
                FileInputStream fis = new FileInputStream(image);
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                byte[] buf = new byte[1024];
                for (int readNum; (readNum = fis.read(buf)) != -1;) {
                    bos.write(buf, 0, readNum);
                }
                person_image = bos.toByteArray();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_MUploadBActionPerformed

    private void MProfilePComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_MProfilePComponentShown
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpd", "root", "Tyagi67@#");
            PreparedStatement ps = con.prepareStatement("select * from managerlogin where Username ='"+Username+"'");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                
                image = rs.getBytes("ProfilePic");
                username = rs.getString("Username");
                empid = rs.getString("EmpId");
                fname = rs.getString("Fullname");
                email = rs.getString("Email");
                phone = rs.getString("Mobile");
                gender = rs.getString("Gender");
                address = rs.getString("Address");
                branch = rs.getString("Branch");
                designation = rs.getString("Designation");  
            }
            ImageIcon format = new ImageIcon(image);
            Image mm = format.getImage();
            Image img2 = mm.getScaledInstance(MPProfilePic.getWidth(), MPProfilePic.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon image = new ImageIcon(img2);
            
            MPProfilePic.setIcon(image);
            MPUsername.setText(username.toUpperCase());
            MPEmpId.setText(empid);
            MPName.setText(fname.toUpperCase());
            MPEmail.setText(email.toUpperCase());
            MPPhone.setText(phone);
            MPGender.setText(gender);
            MPAddress.setText(address.toUpperCase());
            MPBranch.setText(branch.toUpperCase());
            MPDesignation.setText(designation.toUpperCase());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_MProfilePComponentShown

    private void USearchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USearchBActionPerformed
        try {
            String accountNo = UAccountNoSF.getText();
            String Username1 = UUsernameSF.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpd", "root", "Tyagi67@#");
           PreparedStatement ps = con.prepareStatement("select * from customerlogin where Username ='"+Username1+"' OR AccountNumber ='"+accountNo+"'");
           
            ResultSet rs = ps.executeQuery() ;
            if(rs.next()){
                
                accNo = rs.getString("AccountNumber");
                fname = rs.getString("Fullname");
                email = rs.getString("Email");  
                phone = rs.getString("Mobile");
                gender = rs.getString("Gender");
                address = rs.getString("Address");
                state = rs.getString("State");
                district = rs.getString("District");
                country = rs.getString("Country");
                pincode = rs.getString("Pincode");
                acctype = rs.getString("AccType"); 
                username = rs.getString("Username");  
                balance = rs.getString("Balance");  
            
                UAccountNo.setText(accNo);
                UFullname.setText(fname);
                UEmail.setText(email);
                UPhone.setText(phone);
                UGender.setText(gender);
                UAddress.setText(address);
                UState.setText(state);
                UDistrict.setText(district);
                UCountry.setText(country);
                UPincode.setText(pincode);
                UAccType.setSelectedIndex(0);
                UUsername.setText(username);
                UBalance.setText(balance);

        }
            else{
            JOptionPane.showMessageDialog(null,"Record Not Found");
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_USearchBActionPerformed

    private void UUpadateBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UUpadateBActionPerformed
         File f = new File(filename);
        int i =0;
        String AccountNumber = UAccountNo.getText();
        String Fullname = UFullname.getText();
        String Email = UEmail.getText();
        String Mobile = UPhone.getText();
        String Gender = UGender.getText();
        String Address = UAddress.getText();
        String State = UState.getText();
        String District = UDistrict.getText();
        String Country = UCountry.getText();
        String Pincode = UPincode.getText();
        String AccType = UAccType.getSelectedItem().toString();
        String Username = UUsername.getText();
        String Image = UProfilePic.getText();
        String Password = String.valueOf(UPassword.getPassword());
        String Cnfpwd = String.valueOf(UCPassword.getPassword());
        String Balance = UBalance.getText();
            try {
            InputStream is = new FileInputStream(f);
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpd", "root", "Tyagi67@#");
           PreparedStatement ps = con.prepareStatement("update customerlogin set Fullname=?, Email=?,Mobile =?, Gender=?, Address=?,State =?, District=?, Country=?,Pincode =?, AccType=?, Username=?, ProfilePic =?, Password=?, Cnfpwd=?, Balance=? where AccountNumber =?");
                 if (Cnfpwd.equals(Password)) {
                ps.setString(1, Fullname);
                ps.setString(2, Email);
                ps.setString(3, Mobile);
                ps.setString(4, Gender);
                ps.setString(5, Address);
                ps.setString(6, State);
                ps.setString(7, District);
                ps.setString(8, Country);
                ps.setString(9, Pincode);
                ps.setString(10,AccType);
                ps.setString(11, Username);
                ps.setBlob(12, is);
                ps.setString(13, Password);
                ps.setString(14, Cnfpwd);
                ps.setString(15,Balance);
                ps.setString(16,AccountNumber);
                i = ps.executeUpdate();
                System.out.println(i);
            }
            else
            {
                 JOptionPane.showMessageDialog(null, "Please Enter Same Password!");
            }
            if (i == 1) {
            JOptionPane.showMessageDialog(null, "Successfull Updated");
                MAccountNo.setText(" ");
                MFullname.setText(" ");
                MEmail.setText(" ");
                MPhone.setText(" ");
                MGender.setText(" ");
                MAddress.setText(" ");
                MState.setText(" ");
                MDistrict.setText(" ");
                MCountry.setText(" ");
                MPincode.setText(" ");
                MAccType.setSelectedIndex(0);
                MUsername.setText(" ");
                MProfilePic.setText(" ");
                MPassword.setText(" ");
                MCPassword.setText(" ");
                MBalance.setText(" ");
                
            } else {
                JOptionPane.showMessageDialog(null, "Some Error Occured!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_UUpadateBActionPerformed

    private void UPicUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPicUploadActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        int radius= 40;
        filename = f.getAbsolutePath();
        UProfilePic.setText(filename);
        String PATTERN = "^(([a-zA-Z]:)|(\\\\{2}\\w+)\\$?)(\\\\(\\w[\\w].*))(.jpg|.JPG|.png|.PNG|.jpeg|.JPEG)$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(UProfilePic.getText());
        if (!match.matches()) {
            UProfilePic.setText(" Please Select Image in png only!");
            filename = null;
        } else {
            UProfilePic.setText(null);

            ImageIcon imageicon = new ImageIcon(filename);
            Image img = imageicon.getImage().getScaledInstance(2*radius, 2*radius, Image.SCALE_SMOOTH);
            UProfilePic.setText(filename);

            try {
                File image = new File(filename);
                FileInputStream fis = new FileInputStream(image);
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                byte[] buf = new byte[1024];
                for (int readNum; (readNum = fis.read(buf)) != -1;) {
                    bos.write(buf, 0, readNum);
                }
                person_image = bos.toByteArray();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_UPicUploadActionPerformed

    private void ViewTransactonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ViewTransactonComponentShown
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpd", "root", "Tyagi67@#");
            PreparedStatement ps = con.prepareStatement("select AccountNumber, Date, Credit, Debit, ClearBalance from transactions");
            ResultSet rs = ps.executeQuery();
            ATStatement.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_ViewTransactonComponentShown

    private void ViewCustomerDetailComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ViewCustomerDetailComponentShown
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mpd", "root", "Tyagi67@#");
            PreparedStatement ps = con.prepareStatement("SELECT * FROM vcd");
            ResultSet rs = ps.executeQuery();
            Customerlist.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_ViewCustomerDetailComponentShown

    private void ATPrintBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATPrintBActionPerformed
        MessageFormat header = new MessageFormat("All Transactions");
        MessageFormat footer = new MessageFormat("page{0,number,integer}");
        try{
            ATStatement.print(JTable.PrintMode.FIT_WIDTH,header,footer);
            JOptionPane.showMessageDialog(this,"Statement Generated");

        }
        catch(Exception e){

        }

    }//GEN-LAST:event_ATPrintBActionPerformed

    private void CLPrintBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLPrintBActionPerformed
        MessageFormat header = new MessageFormat("All CustomerList");
        MessageFormat footer = new MessageFormat("page{0,number,integer}");
        try{
            Customerlist.print(JTable.PrintMode.FIT_WIDTH,header,footer);
            JOptionPane.showMessageDialog(this,"Statement Generated");

        }
        catch(Exception e){

        }
    }//GEN-LAST:event_CLPrintBActionPerformed

    private void MProfileNavMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MProfileNavMousePressed
        setColor(ind_1);
        resetColor(new JPanel[]{ind_2,ind_3,ind_4,ind_5}, new JPanel[]{AddCustomerNav,UpdateCNav,ViewTransactionNav,ViewCustomerList});
        CMainToggel.setSelectedIndex(0);
    }//GEN-LAST:event_MProfileNavMousePressed

    private void UUsernameSFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UUsernameSFFocusGained
        if (UUsernameSF.getText().equals("Username")){
            UUsernameSF.setText("");
        }
    }//GEN-LAST:event_UUsernameSFFocusGained

    private void UAccountNoSFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UAccountNoSFFocusGained
        if (UAccountNoSF.getText().equals("Account No.")){
            UAccountNoSF.setText("");
        }
    }//GEN-LAST:event_UAccountNoSFFocusGained

    
    
    
    private void setColor(JPanel pane) {
        pane.setBackground(new Color(188,167,251));
    }

    private void resetColor(JPanel[] pane, JPanel[] indicators) {
        for (int i = 0; i < pane.length; i++) {
            pane[i].setBackground(new Color(5, 27, 70));

        }
        for (int i = 0; i < indicators.length; i++) {
            indicators[i].setOpaque(false);
        }

    }
    
    public static void main(String args[]) {
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerMain(Username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ATPrintB;
    private javax.swing.JTable ATStatement;
    private javax.swing.JTabbedPane AddCustomer;
    private javax.swing.JPanel AddCustomerNav;
    private javax.swing.JScrollPane AddCustomerSP;
    private javax.swing.JButton CLPrintB;
    private javax.swing.JTabbedPane CMainToggel;
    private javax.swing.JTable Customerlist;
    private javax.swing.JLabel Exit;
    private javax.swing.JComboBox<String> MAccType;
    private javax.swing.JLabel MAccountNo;
    private javax.swing.JButton MAddUserB;
    private javax.swing.JTextArea MAddress;
    private javax.swing.JTextField MBalance;
    private javax.swing.JPasswordField MCPassword;
    private javax.swing.JTextField MCountry;
    private javax.swing.JTextField MDistrict;
    private javax.swing.JTextField MEmail;
    private javax.swing.JTextField MFullname;
    private javax.swing.JTextField MGender;
    private javax.swing.JTextArea MPAddress;
    private javax.swing.JLabel MPBranch;
    private javax.swing.JLabel MPDesignation;
    private javax.swing.JLabel MPEmail;
    private javax.swing.JLabel MPEmpId;
    private javax.swing.JLabel MPGender;
    private javax.swing.JLabel MPName;
    private javax.swing.JLabel MPPhone;
    private javax.swing.JLabel MPProfilePic;
    private javax.swing.JLabel MPUsername;
    private javax.swing.JPasswordField MPassword;
    private javax.swing.JTextField MPhone;
    private javax.swing.JTextField MPincode;
    private javax.swing.JPanel MProfileNav;
    private javax.swing.JTabbedPane MProfileP;
    private javax.swing.JTextField MProfilePic;
    private javax.swing.JTextField MState;
    private javax.swing.JScrollPane MTransactionT;
    private javax.swing.JButton MUploadB;
    private javax.swing.JTextField MUsername;
    private javax.swing.JPanel Profile;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel Titlebar;
    private javax.swing.JComboBox<String> UAccType;
    private javax.swing.JLabel UAccountNo;
    private javax.swing.JTextField UAccountNoSF;
    private javax.swing.JTextArea UAddress;
    private javax.swing.JTextField UBalance;
    private javax.swing.JPasswordField UCPassword;
    private javax.swing.JTextField UCountry;
    private javax.swing.JTextField UDistrict;
    private javax.swing.JTextField UEmail;
    private javax.swing.JTextField UFullname;
    private javax.swing.JTextField UGender;
    private javax.swing.JPasswordField UPassword;
    private javax.swing.JTextField UPhone;
    private javax.swing.JButton UPicUpload;
    private javax.swing.JTextField UPincode;
    private javax.swing.JTextField UProfilePic;
    private javax.swing.JButton USearchB;
    private javax.swing.JTextField UState;
    private javax.swing.JButton UUpadateB;
    private javax.swing.JTextField UUsername;
    private javax.swing.JTextField UUsernameSF;
    private javax.swing.JPanel UpdateCNav;
    private javax.swing.JTabbedPane UpdateCustomer;
    private javax.swing.JScrollPane UpdateCustomerSP;
    private javax.swing.JTabbedPane ViewCustomerDetail;
    private javax.swing.JPanel ViewCustomerList;
    private javax.swing.JPanel ViewTransactionNav;
    private javax.swing.JTabbedPane ViewTransacton;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JPanel ind_5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logout;
    // End of variables declaration//GEN-END:variables
}
